### ISSUE TITLE
依旧被检出无法使用

### ISSUE THREAD

**Issue by fatinghenji** [lz233/FuckVirtualsim#1]
手机：RedmiK20Pro
rom：稳定版10.3.15
面具版本：7.3.2（224）
使用的是edxposed
riru版本：19.4
edxposed：0.4.5.1_beta(4463)（SandHook）
报错界面：
![image](https://user-images.githubusercontent.com/37131177/61579462-e977bc00-ab37-11e9-84d0-2d92d01d446c.png)

**Comment by lz233** [comment]
机型问题吧。。。
